name: Apprentice
on: [pull_request, issues, issue_comment, pull_request_review]
jobs:
  apprentice:
    runs-on: [ubuntu-latest]
    steps:
      - name: Apprentice Check
        uses: fomantic/apprentice-action@master
