name: Apprentice
on: [issues, issue_comment, pull_request, pull_request_review]
jobs:
  apprentice:
    runs-on: [ubuntu-latest]
    steps:
      - name: Apprentice Check
        uses: fomantic/apprentice-action@master
        with:
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
